services:
  backend:
    image: harbor.gftinnovation.eu/humaine/humaine-al-api:v0.3.3
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MINIO_PREFIX=PROD_TEST
      - MINIO_USERNAME=${MINIO_USERNAME}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
      - DUCKDB_PATH=storage/db/humal.duckdb
      - RABBIT_URL=amqp://guest:guest@host.docker.internal:5672/
      - TASK_QUEUE=xai_jobs
      - RESULT_QUEUE=xai_results
      - USE_RABBITMQ=0
      - MESSAGE_VERSION=0.3
    networks:
      - humal-network

  frontend:
    image: rokklancic/humal-frontend:dev-0.2
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - humal-network

networks:
  humal-network:
    driver: bridge
